# Generated by Django 6.1 on 2026-08-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgerprofile',
            name='is_guardian',
            field=models.BooleanField(default=False),
        ),
    ]
