# Generated by Django 6.1 on 2026-08-12 00:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forgers', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mission_completed', 'Mission completed'), ('reward_redeemed', 'Reward redeemed'), ('manual_adjustment', 'Manual adjustment')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_events', to='forgers.forgerprofile')),
                ('mission_completion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forge_event', to='missions.missioncompletion')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AstralLightLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('earned', 'Earned'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astral_light_ledger_entries', to='forgers.forgerprofile')),
                ('forge_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astral_light_entries', to='forge.forgeevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='astral_light_ledger_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='StarLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forge_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='star_entries', to='forge.forgeevent')),
                ('forger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_ledger_entries', to='forgers.forgerprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='star_ledger_amount_not_zero')],
            },
        ),
    ]
