# Generated by Django 6.1 on 2026-08-12 00:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cadence', models.CharField(choices=[('one_time', 'One time'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='one_time', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_missions', to='forgers.forgerprofile')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_missions', to='forgers.forgerprofile')),
                ('forger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_assignments', to='forgers.forgerprofile')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='missions.mission')),
            ],
            options={
                'ordering': ['forger__display_name', 'mission__title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_on', models.DateField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='missions.missionassignment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_mission_completions', to='forgers.forgerprofile')),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MissionAgeReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult')], max_length=16)),
                ('star_value', models.PositiveSmallIntegerField(default=1)),
                ('astral_light_value', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_rewards', to='missions.mission')),
            ],
            options={
                'ordering': ['mission__title', 'age_group', 'id'],
                'constraints': [models.UniqueConstraint(fields=('mission', 'age_group'), name='unique_mission_age_reward'), models.CheckConstraint(condition=models.Q(('star_value__gte', 0)), name='mission_age_reward_star_value_non_negative'), models.CheckConstraint(condition=models.Q(('astral_light_value__gte', 0)), name='mission_age_reward_astral_light_value_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='missionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('mission', 'forger'), name='unique_active_mission_assignment_per_forger'),
        ),
        migrations.AddConstraint(
            model_name='missioncompletion',
            constraint=models.UniqueConstraint(fields=('assignment', 'completed_on'), name='unique_mission_assignment_completion_per_day'),
        ),
    ]
