# Generated by Django 6.1 on 2026-08-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to='forgers.forgerprofile')),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guardian', 'Guardian'), ('member', 'Member')], default='member', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('removed', 'Removed')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='families.family')),
                ('forger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='forgers.forgerprofile')),
            ],
            options={
                'ordering': ['family__name', 'forger__display_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('family', 'forger'), name='unique_family_forger_membership')],
            },
        ),
    ]
